### PR TITLE
Update Qt to 5.9.3

### PR DESCRIPTION
**Pull request by MatMaul**
Add QtSvg module (needed for recent 3.0 build)
Add QtWayland module

### CODE REVIEW

**Comment by MatMaul** [comment]
I have more updates to send so we can have a nice 3.0 release (RC1 is tagged) :)
I'll wait for #10 to be accepted to send more since it blocks the build.

**Comment by TingPing** [comment]
bot, build

**Comment by MatMaul** [comment]
bot, build

**Comment by MatMaul** [comment]
bot, build

**Comment by MatMaul** [comment]
@alexlarsson is it possible to increase the timeout of 2h to 3 or 4 ?

**Comment by MatMaul** [comment]
Also my last bot build seems to not have trigger a new build, I still see the failed attempts because of the timeout in the dashboard.

**Comment by TingPing** [comment]
The build succeeded though?

**Comment by MatMaul** [comment]
Ok so it seems to have been triggered afterwards, great !

**Pull request merged**
