### PR TITLE
Enable Chromecast support

### LINKED ISSUE #138: VLC won't connect to chromecast
Hello,

I'm not sure if this is a Flatpak security issue (or feature), but I'm not able to connect to my chromecast when using the Flatpak version of VLC. If I use my distro's repo version of VLC it works, but with Flatpak, I get the following error:

'main stream output error: stream chain failed for `chromecast{ip=xxx.xxx.x.xx,port=8009}’

I suspect this has something to do with Flatpak restricting access to the specific port chromecast uses (8009), but hoping there is a way to resolve or enable access somehow.

### PR DESCRIPTION
**Pull request by tinywrkb**
Add missing protobuf dependency for the Chromecast feature.
Closes #138.

### CODE REVIEW

**Comment by tinywrkb** [comment]
bot, build org.videolan.VLC

**Comment by tinywrkb** [comment]
I only tested that this is being built correctly locally, and the Chromecast feature is enabled.  No idea if it's actually working.  

The compiler, `protoc`, might not be needed after compiling VLC, so I can remove it in the cleanup step, and just keep the libraries, but I'll wait first for the CI here to actually work in order to avoid running multiple build jobs at the same time.

**Comment by tinywrkb** [comment]
bot, build org.videolan.VLC

**Comment by tinywrkb** [comment]
Reported back by the user that this is working as expected and solves the issue.  
Ready to be merged.

**Comment by MatMaul** [comment]
Thanks for your contribution @tinywrkb !

**Pull request merged**
