### PR TITLE
update runtime to version 5.15-23.08

### PR DESCRIPTION
**Pull request by christianrauch**

### CODE REVIEW

**Comment by nurupo** [comment]
Correct me if I'm wrong, but I believe we need to make sure that all the plugins have updated to the 23.08 Freedesktop SDK before this can be merged, as otherwise new users will not able to install any plugins on the VLC with updated runtime.

I have added `branch/3-23.08` to my https://github.com/flathub/org.videolan.VLC.Plugin.pause_click. Maintainers of other plugins should update their SDKs too.

How often does Flathub refresh the branches information? The 3-22.08 I have added doesn't show up in `flatpak search org.videolan.VLC.Plugin` yet. Once a day, maybe?

**Comment by nurupo** [comment]
>How often does Flathub refresh the branches information? The 3-22.08 branch I have added doesn't show up in flatpak search org.videolan.VLC.Plugin yet. Once a day, maybe?

If anyone else if curious about this too, I Just checked and it now shows up, so it got updated sometime within the last 26 hours. So once (or more) a day sounds plausible.

**Comment by nurupo** [comment]
Regarding the x86_64 build failure:

 ```
 ./libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 ```

from what I gather it's a common problem with FFmpeg caused by binutils >=2.41 no longer considering FFmpeg's hand-made assembly as valid. It has been patched in more recent versions of FFmpeg in [`effadce6c756247ea8bae32dc13bb3e6f464f0eb`](https://git.videolan.org/?p=ffmpeg.git;a=patch;h=effadce6c756247ea8bae32dc13bb3e6f464f0eb) ([GitHub](https://github.com/FFmpeg/FFmpeg/commit/effadce6c756247ea8bae32dc13bb3e6f464f0eb)).

We should either:
- update FFmpeg to a more recent release version that has this issue patched, which seem to be versions 5.1 and 6.0, or
- manually apply the `effadce6c756247ea8bae32dc13bb3e6f464f0eb` patch on the currently used version of FFmpeg

Sources:
https://trac.ffmpeg.org/ticket/10405
https://sourceware.org/PR30578
https://gcc.gnu.org/PR108941

**Comment by MatMaul** [comment]
Thanks for that.
Yes I need to publish a new branch for all the plugins too.

For FFMPEG I seem to remember that versions >4 are not supported on the 3.0.x branch of VLC, but I may be wrong, to be tested. We may have to embed the patch for now.

**Comment by MatMaul** [comment]
This commit is included in #187 and now merged.

**Pull request closed without merging**
