### PR TITLE
Remove dependencies available in Sdk

### PR DESCRIPTION
**Pull request by Erick555**
Those are available in Sdk/Platform and shouldn't be needed.

### CODE REVIEW

**Comment by Erick555** [comment]
Everything seems to work good. This is ready to merge.

**Comment by MatMaul** [comment]
Looks great, thanks, let's merge this.

**Comment by Erick555** [comment]
@MatMaul It seems the build worked but upload to flathub [failed](https://flathub.org/builds/#/builders/32/builds/1409). You have to somewhat restart it.

**Comment by MatMaul** [comment]
@Erick555 indeed thanks, building again.

**Pull request merged**
