### PR TITLE
Update to 3.0.1 & update dependencies

### PR DESCRIPTION
**Pull request by MatMaul**
The HiDPI scaling patch has also been updated to be a bit less "brutal" by rounding up for value superior or equal to .8 instead of systematic truncation.

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
Already had #24 but I guess this can supersede it.

**Comment by MatMaul** [comment]
the build farm was dead, seems like it didn't go through the build at all.

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
`Failed to download sources: module libavc1394: Wrong sha256 checksum for libavc1394-0.5.4.tar.gz, expected 7cb1ff09506ae911ca9860bef4af08c2403f3e131f6c913a2cbd6ddca4215b53, was 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf`

**Comment by MatMaul** [comment]
This is really weird, why the hash would change ? Officially the file has not changed on sourceforge.net...
Anyway I'll update. I'll also add a patch to fix HTTP interface (patch sent upstream).

**Comment by MatMaul** [comment]
The tar.gz is corrupted... I found a valid debian mirror with the original hash, let's go for that.

**Comment by TingPing** [comment]
bot, build

**Comment by MatMaul** [comment]
Same kind of problem with zvbi, on sourceforge again...
Let's wait tomorrow I think they have a problem.

**Comment by nedrichards** [comment]
bot, build

**Comment by MatMaul** [comment]
We need this commit to fix arm:
http://git.videolan.org/?p=vlc/vlc-3.0.git;a=commit;h=29c4721b18ad422cc3cbb6aed9d321900dab0e51

PR updated ;)

**Comment by TingPing** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by MatMaul** [comment]
The build was still failing on arm64, it should be good now.
https://mailman.videolan.org/pipermail/vlc-devel/2018-March/117992.html

**Comment by nedrichards** [comment]
bot, build

**Comment by MatMaul** [comment]
Still not working... I just reverted the commit introducing the changes for now.
Sorry for that but I have no means for testing the changes.

**Comment by MatMaul** [comment]
up build :)

**Comment by nedrichards** [comment]
bot, build

**Comment by MatMaul** [comment]
Success :)

**Pull request merged**
