### PR TITLE
Use shared-modules/libusb

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by A6GibKm** [comment]
bot, build org.videolan.VLC

**Comment by A6GibKm** [comment]
Since the build method does not change at all, the issue must lie in one of the other packages updated in shared-modules.

**Comment by Erick555** [comment]
lua 5.3 causes issues:
```
lua/demux.c:55:13: error: implicit declaration of function ‘luaL_checkint’; did you mean ‘luaL_checkany’? [-Werror=implicit-function-declaration]
   55 |     int n = luaL_checkint( L, 1 );
      |             ^~~~~~~~~~~~~
      |             luaL_checkany
```

There were many changes for it recently: https://github.com/flathub/shared-modules/commits/master/lua5.3

**Comment by MatMaul** [comment]
Thanks for that @A6GibKm , merged.

**Pull request merged**
