### PR TITLE
Update runtime to 5.15

### PR DESCRIPTION
**Pull request by Erick555**

### CODE REVIEW

**Comment by Erick555** [comment]
@MatMaul this works now, for plugins you need to create 20.08 branches

**Comment by eszlari** [comment]
@MatMaul ping

**Comment by MatMaul** [comment]
Thanks for that, merging. I am going to revert the libplacebo update however because vlc 3 is only supposed to be compatible with 0.2.x ABI wise.

**Comment by MatMaul** [comment]
Nevermind, seems to be regular updates on the code side.

**Pull request merged**
