### PR TITLE
Update VLC, libDSM and srt

### PR DESCRIPTION
**Pull request by MatMaul**

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by MatMaul** [comment]
I removed x265 update since it breaks arm builds.
https://bitbucket.org/multicoreware/x265/issues/406/arm-assembly-fail-to-compile-on-18

**Comment by TingPing** [comment]
bot, build

**Comment by eszlari** [comment]
> I removed x265 update since it breaks arm builds.
> https://bitbucket.org/multicoreware/x265/issues/406/arm-assembly-fail-to-compile-on-18

I could get x265 to compile on arm & arm64 with the two patches attached to that issue when building https://github.com/flathub/org.avidemux.Avidemux (but avidemux itself failed at the end, that's why arm is skipped).

**Comment by MatMaul** [comment]
ok thanks, to be fair it is not a biggy, I'll do it next time I update something. This can be merged I think @TingPing.

**Pull request merged**
