### PR TITLE
remove dconf access

### PR DESCRIPTION
**Pull request by dgcampea**

### CODE REVIEW

**Comment by TingPing** [comment]
VLC itself doesn't use DConf so there is nothing to migrate.

If its deps want DConf access is another question and needs more testing/thought.

**Comment by dgcampea** [comment]
I will do some retesting with dconf access removed then

**Comment by MatMaul** [comment]
I already investigate this, dconf is only used by QGnomePlatform to read the current theme settings.
I ruled against moving to the new Settings portal for now because it brings no added security value (we are already using filesystem=host), and it will break the theming when the portal is not >= v1.1 on the host.
I was planning to do that end of the year. You don't need the migrate path since it is not used by VLC to store conf but only to read some system conf.

**Comment by dgcampea** [comment]
Users can override the filesystem access. In that case this might bring some value

**Comment by MatMaul** [comment]
Thanks, I'll merge that later in the year.

**Comment by TingPing** [comment]
> I already investigate this, dconf is only used by QGnomePlatform to read the current theme settings.

This *shouldn't* be true any more. The KDE portal was developed alongside the Qt support AFAIK, if not this should certainly be reported upstream.

**Comment by MatMaul** [comment]
Indeed it's working perfectly without dconf bindmount if the portal version is >= 1.1, hence why I am waiting a bit. Or you mean something else ?

**Comment by MatMaul** [comment]
let's merge that :) thx for the PR.

**Pull request merged**
