### PR TITLE
Add fresh screenshots

### PR DESCRIPTION
**Pull request by Doomsdayrs**
These fresh screenshots provide a better view of VLC, with GNOME4

Newly added, are windowed/full screen variants

### CODE REVIEW

**Comment by MatMaul** [comment]
I am not against the change, but PNG with a size between 1 and 4MB is a no-go, not everyone is on unrestricted landline fiber :) 
Please resize them down a bit and switch to JPG format so we get to a similar size to the current ones.

**Comment by Doomsdayrs** [comment]
> I am not against the change, but PNG with a size between 1 and 4MB is a no-go, not everyone is on unrestricted landline fiber :) Please resize them down a bit and switch to JPG format so we get to a similar size to the current ones.

Sure thing, Let me get to that

**Comment by Doomsdayrs** [comment]
@MatMaul 

I compressed the images the best I could, but the images of the landscape are more complex, thus the compression could only get them down to about 200kb for those two. 

In total, the new size of all 4 images is 614 kB

**Comment by Doomsdayrs** [comment]
@MatMaul ?

**Comment by nurupo** [comment]
Is there any point in providing such high-res images at all? From my experience, Flathub shrinks the images to be way too small, e.g. [the screenshots for my VLC plugin](https://flathub.org/apps/org.videolan.VLC.Plugin.pause_click) can't even be read on Flathub, which is very annoying.

**Comment by MatMaul** [comment]
@Doomsdayrs yes sorry, I was cleaning up related appdata stuff and thought about merging your PR on the way.

However @nurupo has a point, while the storage size is fine the DPI is too high and we would not see much of VLC UI once it is scaled to the presentation size used by flathub.org or GNOME Software.

Do you mind taking screenshots at 720p instead? I can't downscale from the PNG since it will not get the UI any bigger :) 

I also wanted to ask you if you used free-to-use video content but I googled the title of the videos and everything seems fine on this side.

Sorry for taking so long, I am quite busy and screenshots are a bit of a low hanging fruits so...

**Pull request closed without merging**
