### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by MatMaul**
remove libXcursor, available in base platform.
remove Adwaita theme icons, they were not even exported.
group QT/UI related stuffs together.

### CODE REVIEW

**Comment by TingPing** [comment]
Since we may move to the KDE runtime at some point could you perhaps put all dependencies that would be replaced by that into its own file?

**Comment by MatMaul** [comment]
Done !

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
Also another potential idea, use the KDE runtime now which has most of this and only build the one patched qt bit here?

**Comment by MatMaul** [comment]
I already tried a while back, it is not easily doable.

**Comment by MatMaul** [comment]
Sourceforge is again erratic... I'll use this PR to switch to other mirrors, no more sourceforge.

**Comment by MatMaul** [comment]
Let's merge this one and I'll rebase the update on top.

**Comment by TingPing** [comment]
bot, build

**Comment by MatMaul** [comment]
if the build pass please do not merge directly, I'll split the PR in 2 commits so we can revert the sourceforge changes later if we want.

**Comment by MatMaul** [comment]
The build is successful and I just separated in 2 commits, you can merge.

**Comment by nedrichards** [comment]
bot, build

**Comment by MatMaul** [comment]
up

**Comment by nedrichards** [comment]
bot, build

**Comment by MatMaul** [comment]
Success :)

**Pull request merged**
