### PR TITLE
Add flatpak version check

### PR DESCRIPTION
**Pull request by eszlari**
https://github.com/flathub/org.videolan.VLC/issues/45

### CODE REVIEW

**Comment by TingPing** [comment]
Note it won't actually fix that problem since 0.8 predates this being added.

**Comment by eszlari** [comment]
@TingPing It was added in `0.8.0`: https://github.com/flatpak/flatpak/releases/tag/0.8.0

**Comment by MatMaul** [comment]
bot, build

**Comment by MatMaul** [comment]
I am not sure we really want that. There is still some stable/LTS distribution versions that use flatpak < 0.11.4 in their repos, do we rather have broken open file or nothing at all ?

I clearly have no strong opinion here, if others agree I am fine to merge this.
@TingPing @eszlari @nedrichards

**Comment by eszlari** [comment]
A broken user experience can damage flatpak's reputation (as i have seen on social media).

**Comment by MatMaul** [comment]
Ok let's merge then, I am convinced :)

**Pull request merged**
