### PR TITLE
Update to 3.0.7

### LINKED ISSUE #74: Update to 3.0.7

### PR DESCRIPTION
**Pull request by Erick555**
Fixes #74

### CODE REVIEW

**Comment by MatMaul** [comment]
Thx, can you push this one instead :) ? It's freshhhhh.
http://get.videolan.org/vlc/3.0.7.1/vlc-3.0.7.1.tar.xz

**Comment by MatMaul** [comment]
Or I can do it let me know, just see you are not a new contributor at all so perhaps you don't care about doing it yourself :)

**Comment by Erick555** [comment]
@MatMaul done

**Comment by MatMaul** [comment]
Thanks.

**Pull request merged**
