### PR TITLE
Update to 3.0.2

### PR DESCRIPTION
**Pull request by MatMaul**

### CODE REVIEW

**Comment by MatMaul** [comment]
Indeed, done. I put RelWithDebInfo because the debug symbols are stripped in a separated debug package anyway so it doesn't hurt and can help debugging. @nedrichards I think this is good to test/merge.

**Comment by TingPing** [comment]
Failed: https://flathub.org/builds/#/builders/2/builds/1517

**Comment by MatMaul** [comment]
fixed, sorry.

**Comment by barthalion** [comment]
bot, build

**Pull request merged**
