### PR TITLE
Put better screenshots in the appdata

### PR DESCRIPTION
**Pull request by MatMaul**

### CODE REVIEW

**Comment by Erick555** [comment]
The test build will always fail if it uses paths for master but after merge it should work (assuming those screenshots are legit).

**Comment by TingPing** [comment]
The appstream spec requests 16:9 aspect ratio images: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html#tag-dapp-screenshots

**Comment by TingPing** [comment]
Looks perfect :+1:

**Comment by MatMaul** [comment]
Cool, let's see !

**Pull request merged**
